apiVersion: v1
kind: Service
metadata:
  name: pma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: pma
  ports:
    - protocol: TCP
      name: http
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: pma_img
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user
              key: password
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: user
              key: username