apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21
    - protocol: TCP
      name: ftps-additional
      port: 30021
      targetPort: 30021
    - name: ftps-additional2
      protocol: TCP
      port: 20
      targetPort: 20
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30021
        volumeMounts:
        - name: ftps
          mountPath: /ftp
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps-pv-claim